# Generated by Django 6.0.6 on 2026-06-16 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('source', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('matched_query', models.CharField(blank=True, max_length=255)),
                ('raw_payload', models.JSONField(default=dict)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-ingested_at'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Fire', 'Fire'), ('Flood / Rain Damage', 'Flood / Rain Damage'), ('Road Accident', 'Road Accident'), ('Infrastructure Failure', 'Infrastructure Failure'), ('Power Outage', 'Power Outage'), ('Health / Food Safety', 'Health / Food Safety'), ('Public Safety', 'Public Safety'), ('Other', 'Other')], max_length=100)),
                ('summary', models.TextField()),
                ('severity', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Unknown', 'Unknown')], default='Unknown', max_length=50)),
                ('location_text', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('location_confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=20)),
                ('review_status', models.CharField(choices=[('needs_review', 'Needs Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('edited', 'Edited')], default='needs_review', max_length=20)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('duplicate_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='incidents.incident')),
                ('source_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='incidents.rawarticle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
