# Generated by Django 6.0.6 on 2026-06-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawarticle',
            name='source',
            field=models.CharField(max_length=500),
        ),
    ]
