# Generated by Django 6.0.6 on 2026-06-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_alter_rawarticle_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawarticle',
            name='url',
            field=models.URLField(max_length=2000, unique=True),
        ),
    ]
